version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment: 
      - MONGO_INITDB_DATABASE=users
    volumes:
      - ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initbd.d/init-mongo.js:ro
    
  backend:
    container_name: user_management_backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on: 
      - mongo

  # server:
  #   container_name: user_management_frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - '8080:8080'
  #   depends_on: 
  #     - backend